language: java
jdk:
- oraclejdk8
deploy:
  provider: s3
  upload-dir: output
  bucket: "thistimelastyear"
  access_key_id: "AKIAJY5JRDOYDOJJ3TDQ"
  secret_access_key:
    secure: q99MYlnQ6XcpbrtH6P6kCi9hFDiGYL2AvZWNa4Z31+ZijYNnMe7qoDrj94DMoc5pQiZrroXreeRvl8sz8T0tDP6tqesRuf29tWXl4pIJOnVKtPh+pdEl2MPyHNJXEMVMUNFPmw31l0u9XyUjDIm32sqeiOeQCClHE4t9VgOWFCNW0I37Sezyg3AmUip+hHTUCzsz4klOlMHttkajGy81VTj5fydLIfNCAD27ETuk01O3ZVPQENvBvle7LfDZQk0gGylqjM/LgIGJZs+htGxBUKLphZcCeeQOrw+zhJxSyYJy35YfLpcAvi5hujlxBzAwC1vvWxoXL7xpXJCLGzcxJhOwcFg+UfPPixGPA8Fzn6o6zrAFfCu9hJuXb7t7LLAcdFQ4RAxZE/FymrdRoN4cZkQbNElIVRXN4qHDRTU0yTRJ/3tUQGO+7KLt0G51NYN94yfL3rWSMaiUxSX27RDrvHx4fVNt9cb6DIrV4MKo5t5Oamb1kqomTyTM40qZa42J5ZOTlS9pIaiKsN9GTuJDd8PL1cmZQZZq33ZT+pLBkJrgqiFTSHaFyfTCKK+ioxBvP34cCwtYN+ygakNiCW6e6T+BfPO2qlNQIYAL/HY2QGobwLRSQuai7zyXglk2f8eIhPxjWOgcHJa6aIdoYsjwq62D0MCbK689zUASZiuNt1c=
  provider: bintray
  file: "bintray.json"
  user: "atdavewatts"
   key:
    secure: mgckULPqqPhHu4RLVrPeOP8cAPC8E5IQShef7t8Sv/UsB1qgS8zoMMsA2OSTgOje9DYaTGHJXTZ9LCvdpJM+IPhXDR6RCUWPUjWZjxlcF3QyML3NNdfbSxih6FsONTiGVaWZMFmko+mgqABrZBkPegpd/oA9jQoSGovTSDyqosTRJO2qGFiHqVXWtIV7J6XGPoLb+7Ux6TYX3wzSw32VNIP4z56DRleSmxWlv8p0SZQIMMMWtrOt2wppObYJcxjlQ1qGyvhBySt6GpWR9wPHVoG1RMpvtiz9IkSL4YUjouVutrwqq8SKFFYXuHIzyYeXH2OWCmZChz3lmnOlGWPQ9H2I+GHaOwmEPcZCWLcim98Q7nYlYP7n2XSEzCe5TfppR8DgZ1hQSKtjilBPHB3Ub/54AazfArO5gtwoMgLR19T95JpAgdRn4zoE6p4n+DSzbkdVcJ1zNVnhY2blfIJj91Ut5vjWzOwLqS4uf92LGEoVhwC0bSSX7nAyPRsURziTF1i6wHlFWaVdH7QcSjJ6QcTxM38ouY0pOobE7XHdfg+cW038dgZ/7TmoYSW/cX7jxzx6WxgFWSPma07INI1cRy54cp7SvhbgEk0rCp0m8vxUvVVz3rnChR8zSNH3sWWu905IRT5eAteQdU8npWM6gUCnbgcjOMvRSN03RFc2kw4=
  dry-run: true